// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
import Header from '@/components/admin/Header';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Spaghetti Coding Club',
//   description: "Generated by Kim's Crew",
// };

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex'>
      <Header />
      {children}
    </div>
  );
}
